/**
 * Ground-track contract — a polyline of future positions used to draw the
 * satellite's path over the Earth's surface.
 *
 * @packageDocumentation
 */
import { z } from 'zod';
import { PositionSchema } from './position.js';

/**
 * A sampled future trajectory for a single satellite.
 *
 * Generated by propagating the satellite's TLE forward in fixed time-steps
 * (typically 30 s) for one or two orbital periods (~90 min for LEO). The
 * frontend renders `points` as a path on the globe; consumers should not
 * assume any specific step size and must inspect each `Position.timestamp`.
 *
 * @example
 * ```ts
 * const track: GroundTrack = {
 *   satelliteId: 25544,
 *   points: [
 *     { lat: 35.6, lon: 139.7, alt: 419.7, velocity: 7.66, timestamp: '2026-05-12T14:31:09.000Z' },
 *     { lat: 36.1, lon: 141.8, alt: 419.5, velocity: 7.66, timestamp: '2026-05-12T14:31:39.000Z' },
 *     // ... up to ~180 samples
 *   ],
 * };
 * ```
 */
export const GroundTrackSchema = z
  .object({
    /** NORAD ID of the satellite this track belongs to. */
    satelliteId: z.number().int().positive(),
    /** Ordered list of propagated positions. At least two points so a line can be drawn. */
    points: z.array(PositionSchema).min(2),
  })
  .strict();

/** Inferred type for {@link GroundTrackSchema}. */
export type GroundTrack = z.infer<typeof GroundTrackSchema>;
