/**
 * @orbit-ctrl/types — single source of truth for domain types shared between
 * the frontend, backend, tool registry, and MCP server.
 *
 * All units are SI / standard astronomical conventions:
 * - Distances in kilometers
 * - Speeds in km/s
 * - Angles in degrees (unless otherwise noted)
 * - Timestamps as ISO 8601 strings on the wire, `Date` objects in memory
 *
 * @packageDocumentation
 */

/**
 * A satellite tracked by the system. Backed by a two-line element set (TLE)
 * fetched from Celestrak and refreshed every 24 hours.
 *
 * @example
 * ```ts
 * const iss: Satellite = {
 *   noradId: 25544,
 *   name: 'ISS (ZARYA)',
 *   tle: {
 *     line1: '1 25544U 98067A   24320.50000000  .00012345  00000-0  22345-3 0  9991',
 *     line2: '2 25544  51.6400 123.4567 0001234  12.3456 347.6543 15.50123456 12345',
 *     epoch: '2024-11-15T12:00:00Z',
 *   },
 * };
 * ```
 */
export interface Satellite {
  /** NORAD catalog number — unique integer ID assigned by US Space Command. */
  noradId: number;
  /** Human-readable name as published by Celestrak (e.g., "ISS (ZARYA)"). */
  name: string;
  /** Two-line element set used by SGP4 propagation. */
  tle: TLE;
}

/**
 * Two-line element set — the standard format for satellite orbital elements.
 *
 * See {@link https://en.wikipedia.org/wiki/Two-line_element_set} for the
 * column-level spec. Lines must be passed verbatim to `satellite.js`.
 */
export interface TLE {
  /** Line 1 of the TLE (69 characters, includes drag terms + epoch). */
  line1: string;
  /** Line 2 of the TLE (69 characters, includes orbital elements). */
  line2: string;
  /** ISO 8601 epoch parsed from the TLE for cache invalidation. */
  epoch: string;
}

/**
 * Instantaneous geodetic position of a satellite over Earth.
 *
 * Computed by propagating a {@link Satellite}'s TLE forward to `timestamp`
 * using SGP4, then converting ECI → ECEF → geodetic coordinates.
 *
 * @example
 * ```ts
 * // ISS over Tokyo at altitude ~420 km
 * const pos: Position = {
 *   lat: 35.68,
 *   lon: 139.69,
 *   alt: 419.7,
 *   velocity: 7.66,
 *   timestamp: new Date('2026-05-12T14:31:09Z'),
 * };
 * ```
 */
export interface Position {
  /** Geodetic latitude in degrees, [-90, 90]. Positive north. */
  lat: number;
  /** Geodetic longitude in degrees, [-180, 180]. Positive east. */
  lon: number;
  /** Altitude above WGS-84 ellipsoid in kilometers. */
  alt: number;
  /** Magnitude of velocity vector in km/s. */
  velocity: number;
  /** Time at which this position was computed. */
  timestamp: Date;
}

/**
 * Simulated telemetry sample for a single satellite at one instant.
 *
 * Generated by the Telemetry Simulator at 1 Hz. Values are realistic synthetic
 * data — voltage drops in eclipse, temperature cycles with orbital phase, and
 * attitude rates random-walk around zero. The simulator injects anomalies in
 * ~2% of samples (see {@link Anomaly}).
 */
export interface Telemetry {
  /** NORAD ID of the satellite this telemetry belongs to. */
  satelliteId: number;
  /** Bus voltage in volts. Nominal 24–32 V; drops during eclipse passes. */
  voltage: number;
  /** Internal temperature in degrees Celsius. Cycles -20 °C to +50 °C with orbit. */
  temperature: number;
  /** Body-frame attitude angles in degrees. Small random walk around zero. */
  attitude: Attitude;
  /** Time the sample was generated. */
  timestamp: Date;
}

/**
 * Body-frame attitude (pitch / roll / yaw) of a satellite in degrees.
 *
 * Zero attitude means the body frame is aligned with the local orbital frame.
 * Real satellites maintain attitude within ~0.1° for science payloads.
 */
export interface Attitude {
  /** Rotation about the body Y-axis (nose up/down). */
  pitch: number;
  /** Rotation about the body X-axis (wing up/down). */
  roll: number;
  /** Rotation about the body Z-axis (nose left/right). */
  yaw: number;
}

/**
 * An anomaly detected in a telemetry stream by the Anomaly Engine.
 *
 * Uses a rolling Z-score over 60 samples (1 minute at 1 Hz):
 * - `|Z| > 2` → severity `"warn"`
 * - `|Z| > 3` → severity `"alert"`
 *
 * Three consecutive anomalous samples are required before an alert is emitted
 * to avoid flapping on single-sample noise.
 */
export interface Anomaly {
  /** UUID assigned at detection time. */
  id: string;
  /** NORAD ID of the affected satellite. */
  satelliteId: number;
  /** Which telemetry metric tripped the threshold. */
  metric: TelemetryMetric;
  /** Severity tier — UI uses this to color-code alerts. */
  severity: AnomalySeverity;
  /** Signed Z-score at detection (sign indicates direction of deviation). */
  zscore: number;
  /** Time the anomaly was detected (matches sample timestamp). */
  timestamp: Date;
  /** Human-readable summary for the alert log + agent responses. */
  description: string;
}

/** Telemetry metrics monitored by the Anomaly Engine. */
export type TelemetryMetric = 'voltage' | 'temperature' | 'attitude';

/** Anomaly severity tiers, ordered by escalation. */
export type AnomalySeverity = 'warn' | 'alert';

/**
 * A predicted visible pass of a satellite over a ground observer.
 *
 * Generated by stepping the orbit forward in 60-second increments and
 * recording the contiguous window where elevation > 0°.
 *
 * @example
 * ```ts
 * const pass: Pass = {
 *   satelliteId: 25544,
 *   startTime: new Date('2026-05-12T15:47:00Z'),
 *   endTime: new Date('2026-05-12T15:54:30Z'),
 *   maxElevationDeg: 67.2,
 *   maxElevationAt: new Date('2026-05-12T15:50:45Z'),
 *   durationSeconds: 450,
 * };
 * ```
 */
export interface Pass {
  /** NORAD ID of the satellite making the pass. */
  satelliteId: number;
  /** UTC time the satellite rises above the horizon (elevation = 0°). */
  startTime: Date;
  /** UTC time the satellite sets below the horizon (elevation = 0°). */
  endTime: Date;
  /** Peak elevation angle reached during the pass, in degrees. */
  maxElevationDeg: number;
  /** Time of peak elevation. */
  maxElevationAt: Date;
  /** Total time above the horizon, in seconds. */
  durationSeconds: number;
}

/**
 * Geographic observer location used for pass prediction and "satellites above"
 * queries. Defaults to Tokyo (35.68° N, 139.69° E) in the demo.
 */
export interface ObserverLocation {
  /** Geodetic latitude in degrees, [-90, 90]. */
  lat: number;
  /** Geodetic longitude in degrees, [-180, 180]. */
  lon: number;
  /** Optional altitude above WGS-84 ellipsoid in meters (defaults to 0). */
  altMeters?: number;
}

/**
 * Current space weather snapshot from NOAA Space Weather Prediction Center.
 * Refreshed every 15 minutes.
 *
 * @example
 * ```ts
 * const weather: SpaceWeather = {
 *   kpIndex: 3.1,
 *   solarWind: { speedKmS: 412, densityProtonsCm3: 8.4, bzNanoTesla: -2.1 },
 *   xrayFlux: { class: 'C', magnitude: 2.4 },
 *   summary: 'quiet',
 *   fetchedAt: new Date(),
 * };
 * ```
 */
export interface SpaceWeather {
  /**
   * Planetary K-index, 0–9. Logarithmic scale of geomagnetic disturbance.
   * Values ≥ 5 indicate a geomagnetic storm.
   */
  kpIndex: number;
  /** Real-time solar wind parameters from DSCOVR / ACE at L1. */
  solarWind: SolarWind;
  /** GOES X-ray flux from the active solar X-ray sensor. */
  xrayFlux: XRayFlux;
  /** Coarse summary used for UI badges + agent responses. */
  summary: WeatherSummary;
  /** When this snapshot was retrieved from NOAA. */
  fetchedAt: Date;
}

/** Solar wind plasma parameters measured at L1. */
export interface SolarWind {
  /** Bulk speed in km/s. Quiet ≈ 350, fast streams ≈ 700+. */
  speedKmS: number;
  /** Proton number density in particles per cubic centimeter. */
  densityProtonsCm3: number;
  /**
   * Z-component of interplanetary magnetic field in nanotesla.
   * Sustained negative Bz drives geomagnetic storms.
   */
  bzNanoTesla: number;
}

/**
 * GOES X-ray flux observation, expressed in the standard solar flare
 * letter-class scale.
 *
 * - `A`: 1e-8 W/m² (quiet)
 * - `B`: 1e-7 W/m²
 * - `C`: 1e-6 W/m²
 * - `M`: 1e-5 W/m² (medium flare — can disrupt HF radio)
 * - `X`: 1e-4 W/m² (major flare — radiation storm risk)
 */
export interface XRayFlux {
  class: 'A' | 'B' | 'C' | 'M' | 'X';
  /** Mantissa within the class band, e.g., M2.4 → magnitude 2.4. */
  magnitude: number;
}

/** Coarse space-weather summary used for UI badges and agent narration. */
export type WeatherSummary = 'quiet' | 'unsettled' | 'active' | 'storm';

/**
 * Discriminated-union envelope for WebSocket messages emitted by the API.
 * The `type` field tells the client how to interpret `data`.
 *
 * @example
 * ```ts
 * ws.onmessage = (event) => {
 *   const msg = JSON.parse(event.data) as WSMessage;
 *   switch (msg.type) {
 *     case 'telemetry': handleTelemetry(msg.data); break;
 *     case 'alert':     handleAnomaly(msg.data);   break;
 *   }
 * };
 * ```
 */
export type WSMessage =
  | { type: 'telemetry'; data: Telemetry[] }
  | { type: 'alert'; data: Anomaly }
  | { type: 'positions'; data: SatellitePositionUpdate[] };

/**
 * Position update payload pushed to clients viewing the live globe. Pairs the
 * satellite's NORAD ID with its current {@link Position}.
 */
export interface SatellitePositionUpdate {
  satelliteId: number;
  position: Position;
}
