/**
 * Pass prediction contracts.
 *
 * @packageDocumentation
 */
import { z } from 'zod';

/**
 * A predicted visible pass of a satellite over a ground observer.
 *
 * Generated by stepping the orbit forward in 60-second increments and
 * recording the contiguous window where elevation > 0°.
 *
 * @example
 * ```ts
 * const pass: Pass = {
 *   satelliteId: 25544,
 *   startTime: '2026-05-12T15:47:00.000Z',
 *   endTime: '2026-05-12T15:54:30.000Z',
 *   maxElevationDeg: 67.2,
 *   maxElevationAt: '2026-05-12T15:50:45.000Z',
 *   durationSeconds: 450,
 * };
 * ```
 */
export const PassSchema = z
  .object({
    /** NORAD ID of the satellite making the pass. */
    satelliteId: z.number().int().positive(),
    /** ISO 8601 time the satellite rises above the horizon (elevation = 0°). */
    startTime: z.string().datetime(),
    /** ISO 8601 time the satellite sets below the horizon (elevation = 0°). */
    endTime: z.string().datetime(),
    /** Peak elevation angle reached during the pass, in degrees. */
    maxElevationDeg: z.number().min(0).max(90),
    /** ISO 8601 time of peak elevation. */
    maxElevationAt: z.string().datetime(),
    /** Total time above the horizon, in seconds. */
    durationSeconds: z.number().positive(),
  })
  .strict();

/** Inferred type for {@link PassSchema}. */
export type Pass = z.infer<typeof PassSchema>;
